spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/ebidding_account?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
  jpa:
    show-sql: true

server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
ebidding:
  signing-secret: 123456
  hash-key: 123456