spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/account/**
        - id: bid-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/bid/**
          filters:
            - JWTFilter
        - id: bwic-service
          uri: http://localhost:8099
          predicates:
            - Path=/api/v1/bwic/**
          filters:
            - JWTFilter
        - id: ebidding-ui
          uri: http://localhost:3000
          predicates:
            - Path=/**
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
  port: 80