apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricer-svc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricer-svc
      env: test
  template:
    metadata:
      labels:
        app: pricer-svc
        env: test
    spec:
      containers:
        - name: pricer-svc
          image: ebidding/pricer-svc
          imagePullPolicy: Never
          ports:
            - name: http-port
              containerPort: 80
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 600Mi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: common-config
---
apiVersion: v1
kind: Service
metadata:
  name: pricer-service
spec:
  selector:
    app: pricer-svc
    env: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80